import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Toaster } from '@repo/ui/toast';

import { DesktopNavigation } from '../components/shared/DesktopNavigation';
import './app.css';

const inter = Inter({
  subsets: ['latin'],
  preload: true,
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-custom-sans',
});

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DesktopNavigation />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
