FROM node:22.14-alpine AS base

FROM base AS builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" PNPM_VERSION="10.2.1" sh -
RUN pnpm install turbo@2.4.1 --global
WORKDIR /builder
COPY . .
RUN turbo prune server --docker

FROM builder AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /installer

COPY --from=builder /builder/out/json/ .
RUN pnpm install

COPY --from=builder /builder/out/full/ .
RUN turbo run build --filter=server

FROM base AS runner
WORKDIR /app

# RUN addgroup --system --gid 1001 server
# RUN adduser --system --uid 1001 server
# USER server
COPY --from=installer /installer .

CMD [ "sleep", "infinity" ]
