name: "monorepo-starter"

volumes:
  database_data:
  cache_data:

services:
  database:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
    restart: unless-stopped
  cache:
    image: valkey/valkey:8.0.2-alpine
    ports:
      - "6379:6379"
    environment:
      VALKEY_EXTRA_FLAGS: --save 60 1 --loglevel warning
    volumes:
      - cache_data:/data
    restart: unless-stopped
