name: 'monorepo-starter'

volumes:
  database_data:
  cache_data:

services:
  database:
    container_name: database
    image: postgres:17.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
    depends_on:
      - cache
    restart: unless-stopped
  cache:
    container_name: cache
    image: redis:7.4.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
