name: monorepo-starter

volumes:
  postgres_data:
  cache_data:

services:
  postgres:
    hostname: monorepo-starter-postgres
    container_name: monorepo-starter-postgres
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
  redis:
    hostname: monorepo-starter-redis
    container_name: monorepo-starter-redis
    image: redis:7.4.2-alpine
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    env_file:
      - .env
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
