name: 'monorepo-starter'

volumes:
  database_data:
  cache_data:

services:
  database:
    hostname: 'monorepo-starter-database'
    container_name: 'monorepo-starter-database'
    image: postgres:17.2-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
    depends_on:
      cache:
        condition: service_started
    env_file:
      - .env

    restart: unless-stopped
  cache:
    hostname: 'monorepo-starter-cache'
    container_name: 'monorepo-starter-cache'
    image: redis:7.4.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache_data:/data
    env_file:
      - .env
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
