name: Quality Control

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-control:
    runs-on: ubuntu-22.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      NODE_VERSION: ${{ vars.NODE_VERSION }}
      PNPM_VERSION: ${{ vars.PNPM_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check dependencies
        run: pnpm exec manypkg check

      - name: Build build:package
        run: pnpm exec turbo build:package --cache=remote:rw

      - name: Lint code
        run: pnpm exec turbo lint --cache=remote:rw

      - name: Check types
        run: pnpm exec turbo check-types --cache=remote:rw
